### ISSUE TITLE
"Both doses and responses should be numeric" when passing a tibble to dr4pl()

### ISSUE THREAD

**Issue by chrbknudsen** [cran/dr4pl#1]
This throws an error
tibble(dose= 1:10, response = 1:10) %>% 
  dr4pl(dose, response)

tibble(dose= 1:10, response = 1:10) %>% 
  as.data.frame() %>%
  dr4pl(dose, response)

solves the problem - but I'm a bit confused as to why the problem occurs in the first place.

**Comment by gaborcsardi** [comment]
Hi, this is a read-only mirror of CRAN, please see the package authors in the DESCRIPTION file.

**Comment by chrbknudsen** [comment]
Of course. Sorry.
