### ISSUE TITLE
predict using dr4pl model

### ISSUE THREAD

**Issue by michaelcvermeulen** [cran/dr4pl#2]
Hello,

I'm looking to place multiple dr4pl dose response curves onto a single ggplot. 
In the past, when using the drc package, I used the predict function to build the curves, which were added individually. 

There is the thread that addresses the issue, but I cannot get these solutions to run properly. 

Is there an established way to add multiple dr4pl curves to a single plot?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by michaelcvermeulen** [comment]
oops
